### ISSUE TITLE
Latest changes on generating version.h breaks embedding

### ISSUE THREAD

**Issue by wargio** [libinjection/libinjection#31]
Hello, the latest changes (https://github.com/libinjection/libinjection/commit/bd86522711f6fd2b5f257023e19627fd6c1d5ca0) completely break embedding the files into other projects, like naxsi.

I have been using this lib for a loooong time within naxsi (an NGINX FOSS WAF) and the latest changes completely break the compatibility with other software using this library source code without actually building the .so/.a library.

i would suggest to create a default `version.h` file which gets overwritten by the configure script.
The issue with building this without actually building the library is due how NGINX plugins build system is done which does not simply allow to build the lib first and then link to it easily like any other good build system.

**Comment by fzipi** [comment]
Hey @wargio! There was no release yet after that change, and we are fixing additional things afterwards. You should probably be good with the latest release in the releases page, right?

**Comment by fzipi** [comment]
Also, the file `version.h` is being created by the autoconf tooling in the `src` directory.

**Comment by wargio** [comment]
yes, i understand, but i use this lib via git submodule. right now i'm pointing to the commit before the addition to autotool. but i think the version.h should be either set via compiler flag or allow to have an empty version number for code embedding purposes.
It is true that i should be pointing to the latest release, but still, if this goes into the next release like this, it will require people to patch the file before using it, which is kinda annoying tbh (unless you plan to stop supporting embedding).

**Comment by fzipi** [comment]
I don't think there is a plan to stop embedding. But this was a big move and we are still fixing this kind of detail. So your issue is right in the money. No dates for anything yet, but this should be covered properly.

**Comment by fzipi** [comment]
JFYI: while there is no definition for `VERSION`, there is one for `PACKAGE_VERSION`:
```
...
libtool: compile:  gcc -DPACKAGE_NAME=\"libinjection\" -DPACKAGE_TARNAME=\"libinjection\" -DPACKAGE_VERSION=\"3.9.2.54-6a29-dirty\" "-DPACKAGE_STRING=\"libinjection 3.9.2.54-6a29-dirty\"" -DPACKAGE_BUGREPORT=\"https://github.com/libinjection/libinjection/issues\" -DPACKAGE_URL=\"https://github.com/libinjection/libinjection\" -DPACKAGE=\"libinjection\" -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_MALLOC=1 -DHAVE_MEMCHR=1 -DHAVE_MEMSET=1 -DHAVE_STRCHR=1 -DHAVE_STRSTR=1 "-D__STDC_FORMAT_MACROS=/**/" -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DVERSION=PACKAGE_VERSION_FULL -I. -g -O2 -g1 -O3 -pedantic -fpic -Weverything -Wno-unused-macros -Wno-padded -Wno-covered-switch-default -Wno-poison-system-directories -Wno-disabled-macro-expansion -Wno-unused-local-typedefs -O0 -MT libinjection_sqli.lo -MD -MP -MF .deps/libinjection_sqli.Tpo -c libinjection_sqli.c -o libinjection_sqli.o >/dev/null 2>&1
```

**Comment by fzipi** [comment]
Hi @wargio! Can you try #43 and see if it fixes this problem?

**Comment by wargio** [comment]
Hello @fzipi 
i just tried and it seems working correctly!

**Comment by fzipi** [comment]
Thanks for confirming!
