### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [libinjection/libinjection#32]
Would you like to add more error handling for return values from functions like the following?
* [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [print_html5_token](https://github.com/libinjection/libinjection/blob/49904c42a6e68dc8f16c022c693e897e4010a06c/src/html5_cli.c#L103)
* [printf](https://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output") ⇒ [print_string](https://github.com/libinjection/libinjection/blob/bd86522711f6fd2b5f257023e19627fd6c1d5ca0/src/sqli_cli.c#L23)

**Comment by fzipi** [comment]
@elfring Yes, of course. Do you want to send a PR yourself?

**Comment by elfring** [comment]
* :thinking: How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?
* :crystal_ball: How will chances evolve to benefit any more also from [the means of aspect-oriented software development](https://en.wikipedia.org/wiki/Aspect-oriented_programming "Documentation")?

**Comment by fzipi** [comment]
Sorry, do you have some specific proposal in mind?

**Comment by elfring** [comment]
:thinking: I assume that you could be aware that [error detection](https://en.wikipedia.org/wiki/Cross-cutting_concern#Examples "Documentation") belongs to known cross-cutting concerns.

**Comment by fzipi** [comment]
🤷 Sorry, do you have some specific proposal in mind? Like a PR, or something to discuss that is not a pointer to wikipedia?

**Comment by elfring** [comment]
>…, or something to discuss …

:thought_balloon: I got the impression that contributors of this software are struggling also with known properties of the programming language “C”.

Higher level development tools are evolving to avoid and adapt recurring programming challenges.

**Comment by fzipi** [comment]
Honestly, I don't know what you want here.

Looks like you have time to search for stuff in Wikipedia, but you came here to complain, and not contribute.

This has been a barely maintained library for a very long time. We started merging contributions. Do you really want to contribute? Send a PR.

**Comment by fzipi** [comment]
Please do whatever you think will benefit the project. When you have a concrete PR to send, please open one and tag me.
