### ISSUE TITLE
Add fuzzing

### ISSUE THREAD

**Issue by fzipi** [libinjection/libinjection#39]
We should evaluate if fuzz testing can be added to the library.

**Comment by IvanNardi** [comment]
If it might be useful, nDPI project (which used libinjection internally) already fuzz (some of) libinjection via a trivial fuzzer: https://github.com/ntop/nDPI/blob/dev/fuzz/fuzz_libinjection.c.
#33 has been found this way.

Bottom line: add some fuzzers should be easy.

My 2 cents

**Comment by fzipi** [comment]
This is really helpful, thanks @IvanNardi.

Do you want to take the lead and push a starting example?

**Comment by IvanNardi** [comment]
@fzipi, pushed a first effort. Still work-on-progress

**Comment by fzipi** [comment]
We can close this one after #40.
