### ISSUE TITLE
Having Python 3 workable

### ISSUE THREAD

**Issue by zimmerle** [libinjection/libinjection#4]
**libInjection** uses Python in two different circumstances:

 * Build and test utilities - Build and test utilities are mostly used during library development (vide [misc](https://github.com/libinjection/libinjection/tree/main/misc) folder).
 * Python Bindings - Export the library functionalities to Python.

The support for Python is currently targeting Python 2 using [swig](http://www.swig.org/). This issue is meant to track the progress of having the bindings working all right on Python 3.

Reference:
https://github.com/libinjection/libinjection/blob/991433e7f0cd8db3ad24f1b0c429881d44251505/python/Makefile#L29-L31

The motivation for this issue was: client9/libinjection#108

**Comment by zimmerle** [comment]
Related content: swig/swig#695

**Comment by zimmerle** [comment]
Moving the Python bindings towards its [own repository](https://github.com/libinjection/libinjection-py).

**Comment by fzipi** [comment]
@zimmerle Are you removing the python bindings from the master branch? I have a small patch for the build part, if you want it.

**Comment by zimmerle** [comment]
@fzipi more than welcomed. The idea is to have the bindings in a separated project, facilitating the package releases and issues management.

We started to make the currently bindings to be also workable on py3.

**Comment by fzipi** [comment]
Cool, created #8
