### ISSUE TITLE
XSS vs SQLI: NULL bytes

### ISSUE THREAD

**Issue by IvanNardi** [libinjection/libinjection#44]
Since 991433e it is clear that the input of `libinjection_xss()` MUST be something like `s, strlen(s)`. In other words, we can't have NULL bytes in the input string (see also the discussion in https://github.com/client9/libinjection/issues/150)
Does the same constrain apply to `libinjection_sqli()`?

**Comment by mirkodziadzka-avi** [comment]
I don't think that 991433e7f0cd8db3ad24f1b0c429881d44251505 suggest that we can not have `\0` in the string. It only requires that their must be a terminating `\0`.  If the `\0` is not there, @michaelgranzow-avi found some issues when fuzzing.

In modsec, the use case is calling this from C++ with `input.c_str(), input.length()`. So we can have a `\0` in the input.

**Comment by michaelgranzow-avi** [comment]
From the doxygen comment of `int libinjection_xss(const char* s, size_t slen)`:
```
 * \param[in] s  input string, may contain nulls, does not need to be null-terminated
 * \param[in] slen input string length
 * \return 1 if XSS found, 0 if benign
```

**Comment by IvanNardi** [comment]
> From the doxygen comment of `int libinjection_xss(const char* s, size_t slen)`:
> 
> ```
>  * \param[in] s  input string, may contain nulls, does not need to be null-terminated
>  * \param[in] slen input string length
>  * \return 1 if XSS found, 0 if benign
> ```

Where does it came from? It is quite different from the comment in the code :(
```
 * const char* s: is expected to be a null terminated string.
 * size_t len: should represent the length of the string
 *             without the null terminator - strlen(s). 
```

**Comment by michaelgranzow-avi** [comment]
https://github.com/libinjection/libinjection/blob/main/src/libinjection.h

**Comment by IvanNardi** [comment]
> https://github.com/libinjection/libinjection/blob/main/src/libinjection.h
> 
> What you quoted was added later, and I don't think it's correct. The original idea was certainly to support NULL bytes in strings and to work on strings that are not null-terminated. It doesn't even require that comment, we can conclude that from the signature: why else would `slen` be needed?

That makes sense, I agree. But it seems that the comment has been updated because of  https://github.com/client9/libinjection/issues/150, especially https://github.com/client9/libinjection/issues/150#issuecomment-682196188 [definitely not an expert here, I am only trying to understand the right way to use the API]

**Comment by IvanNardi** [comment]
Since you all agrees that NULL bytes are allowed, should I send a PR to remove that comment?

**Comment by IvanNardi** [comment]
> Hi @IvanNardi. Did you sent the PR?

@fzipi: done now; I was waiting for an explicit ack...
